services:
  - type: worker
    name: trading-bot
    plan: free
    runtime: docker
    envVars:
      - key: BOT_PATH
        value: BINANCE/bot_3.py
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_API_SECRET
        sync: false
      - key: KUCOIN_API_KEY
        sync: false
      - key: KUCOIN_API_SECRET
        sync: false
      - key: KUCOIN_API_PASSPHRASE
        sync: false
      - key: KUCOIN_ETH_ACC
        sync: false
      - key: KUCOIN_KCS_ACC
        sync: false
      - key: KUCOIN_BTC3L_ACC
        sync: false
      - key: KUCOIN_FIAT_ACC
        value: 612a5bd4fdacf4000769936e
